eureka:
    client:
        fetchRegistry: true
        registerWithEureka: true
        serviceUrl:
            defaultZone: http://eurekaserver:8070/eureka/
    instance:
        preferIpAddress: true
example:
    property: I AM THE DEFAULT
logging:
    config: classpath:logback-delayed.xml
logstash:
    host: 3.136.161.26:5000
management:
    endpoints:
        enabled-by-default: true
        web:
            exposure:
                include: '*'
redis:
    port: 6379
    server: ostock-redis.ymengq.0001.use1.cache.amazonaws.com
security:
    oauth2:
        client:
            grant-type: client_credentials
        resource:
            userInfoUri: http://authenticationservice:8082/user
signing:
    key: '"345345fsdfsf5345"'
spring:
    cloud:
        loadbalancer:
            ribbon:
                enabled: false
        stream:
            bindings:
                inboundOrgChanges:
                    content-type: application/json
                    destination: orgChangeTopic
                    group: licensingGroup
            kafka:
                binder:
                    brokers: kafka
                    zkNodes: kafka
    database:
        driverClassName: org.postgresql.Driver
    datasource:
        platform: postgres
        testWhileIdle: true
        validationQuery: SELECT 1
    jpa:
        database: POSTGRESQL
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    sleuth:
        sampler:
            percentage: 1
    zipkin:
        baseUrl: http://zipkin:9411