server:
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    datasource:
      username: sa
      password:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:tcp://localhost/~/test
  config:
    activate:
      on-profile: dev

me.leedo:
  name: LeeYoungHoon
  age: 29
  birthYear: 2397